#!/usr/bin/env bash

# symlink neovim config to ~/.vim
ln -sf "$HOME/.vim" "$HOME/.config/nvim"

# compile ~/.zshrc and ~/.zprofile
zsh -c "zcompile $HOME/.zshrc; zcompile $HOME/.zprofile; zcompile $HOME/.zlogin"

# regenerate compdump
# compile ~/.zsh
zsh -c "source $XDG_DATA_HOME/zgenom/zgen.zsh && zgen compile ${HOME}/.zsh"
