#!/usr/bin/env bash

# symlink neovim config to ~/.vim
ln -sf "$HOME/.vim" "$HOME/.config/nvim"

# compile ~/.zshrc and ~/.zprofile
zsh -c "zcompile $HOME/.zshrc; zcompile $HOME/.zprofile; zcompile $HOME/.zlogin"
# compile ~/.zsh
zsh -c 'for file in $HOME/.zsh/**/*.zsh; do zcompile $file ; done'
