#!/usr/bin/env bash

# shellcheck source=../scripts/files.sh
source "$DOTFILES/scripts/files.sh"

git_root="$(git rev-parse --show-toplevel)"
cmd="$git_root/Pods/SwiftFormat/CommandLineTool/swiftformat"

if [ ! -x "$cmd" ]; then
	cmd=swiftformat
fi

# File is only to find the correct config.
FILE="$1"
shift
filename='.swiftformat'

CONFIG=$(get_config_file "$filename" "$FILE")

if [ -f "$CONFIG" ]
then
	"$cmd" --quiet --config "$CONFIG" "$@"
else
	"$cmd" --quiet "$@"
fi
