#!/usr/bin/env bash

preview="git stash show \$(echo {} | sed 's/stash@{\(.*\)}: .*/\1/') --color -p | my_delta"

git stash list | fzf +1 --preview="$preview" | sed 's/stash@{\(.*\)}: .*/stash@{\1}/'
